/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'User' at '12/20/16 11:15 AM' with Gradle 2.14.1
 *
 * @author User, @date 12/20/16 11:15 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
